# HAL configuration
# Full config docs: https://github.com/marcopeg/hal/blob/main/docs/config/README.md

providers:
  codex: null
  opencode: null

globals:
  access:
    allowedUserIds:
      - ${USER_MARCO_IPHONE_ID}
  engine:
    name: opencode
    model: opencode/gpt-5-nano

projects:
  obsidian:
    cwd: ./obsidian
    telegram:
      botToken: ${OBSIDIAN_TELEGRAM_TOKEN}
  timetracker:
    active: false
    cwd: ./timetracker
    engine:
      name: codex
    telegram:
      botToken: ${TIMETRACKER_TELEGRAM_TOKEN}
