providers:
  codex: null
  opencode: null
  copilot:
    - name: gpt-5-mini
    - name: gpt-5.2
    - name: gpt-5.1-codex-mini
    - name: gpt-5.3-codex
globals:
  access:
    allowedUserIds:
      - ${USER_MARCO_IPHONE_ID}
  engine:
    name: opencode
    model: opencode/gpt-5-nano
projects:
  obsidian:
    cwd: ./obsidian
    telegram:
      botToken: ${OBSIDIAN_TELEGRAM_TOKEN}
    engine:
      name: opencode
      model: github-copilot/gpt-5.3-codex
    commands:
      npm:
        enabled: true
        whitelist:
          - hello
          - world
  timetracker:
    active: false
    cwd: ./timetracker
    engine:
      name: codex
      model: gpt-5.3-codex
    telegram:
      botToken: ${TIMETRACKER_TELEGRAM_TOKEN}
    # Enable /npm command with a whitelist of allowed scripts
    
